version: '3.9'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  file_agent:
    build:
      context: .
      dockerfile: Dockerfile.file
    ports:
      - "8000:8000"
    depends_on:
      - redis

  search_agent:
    build:
      context: .
      dockerfile: Dockerfile.search
    ports:
      - "8001:8001"
    depends_on:
      - redis
